// Generated by scripts/layouts.mjs --generate (seeded, so it is reproducible). Do not edit by hand:
// node scripts/layouts.mjs proves each one is winnable with the same hotspot clicks.
export const VARIANTS = {
  'level_2_pie': [
    {
      items: [
        {
          type: 'sink',
          x: -5.4,
          z: 2.6
        },
        {
          type: 'stove',
          x: 5.5,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: 4.7,
          z: 0.6,
          w: 2.4,
          yaw: -0.35
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 1.6,
              z: [
                -2.8,
                1.5
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: -1.6,
          z: 6.2,
          decor: true
        },
        {
          type: 'saltbox',
          x: 10.5,
          z: 6.2,
          n: 1,
          decor: true
        }
      ],
      board: [
        -3.7,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'sink',
          x: -5.4,
          z: 2.6
        },
        {
          type: 'stove',
          x: 3.3,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: 3.4,
          z: 1.8,
          w: 2.4,
          yaw: 0.05
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 6.5,
              z: [
                -2.8,
                1.5
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: -1.1,
          z: 5.9,
          decor: true
        },
        {
          type: 'saltbox',
          x: 4.4,
          z: 0.7,
          n: 1,
          decor: true
        }
      ],
      board: [
        -0.8,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'sink',
          x: -5.4,
          z: 2.6
        },
        {
          type: 'stove',
          x: 2.6,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: -9.2,
          z: 5.9,
          w: 2.4,
          yaw: 0.35
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 7.4,
              z: [
                -2.8,
                1.5
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: 12.4,
          z: 6.3,
          decor: true
        },
        {
          type: 'saltbox',
          x: -4.6,
          z: 6.4,
          n: 1,
          decor: true
        }
      ],
      board: [
        -0.1,
        0,
        -1.4
      ]
    }
  ],
  'level_3_shadow': [
    {
      items: [
        {
          type: 'stove',
          x: 0,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: -1.6,
          z: -0.4,
          w: 2.2,
          yaw: 0.1
        },
        {
          type: 'wall',
          x: 4.8,
          z: 4.4,
          along: 'z',
          n: 3,
          rows: 2,
          yaw: 0.15
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: -4.8,
              z: [
                -2.8,
                -0.2
              ]
            },
            {
              x: 6.6,
              z: [
                3.9,
                6.8
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: -7,
          z: 5.1,
          n: 2,
          decor: true
        },
        {
          type: 'bowl',
          x: -3.9,
          z: 2.5,
          decor: true
        }
      ],
      board: null
    },
    {
      items: [
        {
          type: 'stove',
          x: 0,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: 4.7,
          z: 3.9,
          w: 2.2,
          yaw: 0.2
        },
        {
          type: 'wall',
          x: -6.6,
          z: 6.1,
          along: 'x',
          n: 3,
          rows: 2,
          yaw: 0.1
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: -1.7,
              z: [
                -2.8,
                -0.2
              ]
            },
            {
              x: -3.7,
              z: [
                3.9,
                6.8
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: 6.9,
          z: 6.2,
          n: 2,
          decor: true
        },
        {
          type: 'bowl',
          x: 11.4,
          z: 6.6,
          decor: true
        }
      ],
      board: null
    },
    {
      items: [
        {
          type: 'stove',
          x: 0,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'hurdle',
          x: 4.2,
          z: -0.5,
          w: 2.2,
          yaw: 0.35
        },
        {
          type: 'wall',
          x: -8.2,
          z: 4.8,
          along: 'x',
          n: 3,
          rows: 2,
          yaw: 0.2
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: -5.2,
              z: [
                -2.8,
                -0.2
              ]
            },
            {
              x: 3.8,
              z: [
                3.9,
                6.8
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: -8.2,
          z: 3.3,
          n: 2,
          decor: true
        },
        {
          type: 'bowl',
          x: 5.4,
          z: 1.2,
          decor: true
        }
      ],
      board: null
    }
  ],
  'level_4_lesion': [
    {
      items: [
        {
          type: 'stove',
          x: 8.9,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'wall',
          x: 5.3,
          z: 6,
          along: 'z',
          n: 2,
          rows: 3,
          yaw: -0.15
        },
        {
          type: 'hurdle',
          x: 7.4,
          z: 1.9,
          w: 2,
          yaw: 0.25
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 13.8,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: -5.5,
              z: [
                4.6,
                7.9
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: -0.7,
          z: 5.6,
          n: 2
        }
      ],
      board: [
        8.9,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'stove',
          x: 7.5,
          z: 5.9,
          yaw: 0.05
        },
        {
          type: 'wall',
          x: 14.1,
          z: 4.6,
          along: 'z',
          n: 2,
          rows: 3,
          yaw: 0.05
        },
        {
          type: 'hurdle',
          x: -1.8,
          z: 6.5,
          w: 2,
          yaw: 0.2
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 12.9,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: -6.2,
              z: [
                4.6,
                7.9
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: 13.1,
          z: 2.6,
          n: 2
        }
      ],
      board: [
        9.3,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'stove',
          x: 7.4,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'wall',
          x: 10.6,
          z: 1.8,
          along: 'x',
          n: 2,
          rows: 3,
          yaw: 0.2
        },
        {
          type: 'hurdle',
          x: 0.5,
          z: 5.6,
          w: 2,
          yaw: -0.15
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 6,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: -6.1,
              z: [
                4.6,
                7.9
              ]
            }
          ]
        },
        {
          type: 'saltbox',
          x: 12.8,
          z: 5.1,
          n: 2
        }
      ],
      board: [
        -6.5,
        0,
        -1.4
      ]
    }
  ],
  'level_5_threshold': [
    {
      items: [
        {
          type: 'stove',
          x: -1.1,
          z: 5.9,
          yaw: -0.05
        },
        {
          type: 'saltbox',
          x: -5.8,
          z: 6.2,
          n: 2,
          offset: 1
        },
        {
          type: 'wall',
          x: 3.6,
          z: 3.6,
          along: 'x',
          n: 3,
          rows: 2,
          yaw: 0.1
        },
        {
          type: 'hurdle',
          x: 9.4,
          z: 5.9,
          w: 2.6,
          yaw: 0.05
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 2.9,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: -8.7,
              z: [
                3.8,
                7.6
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: 7.2,
          z: 3.6
        }
      ],
      board: [
        -3.2,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'stove',
          x: -0.6,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'saltbox',
          x: -8.6,
          z: 5.1,
          n: 2,
          offset: 1
        },
        {
          type: 'wall',
          x: 3.6,
          z: 3.9,
          along: 'z',
          n: 3,
          rows: 2,
          yaw: -0.3
        },
        {
          type: 'hurdle',
          x: -4.8,
          z: 2.3,
          w: 2.6,
          yaw: -0.35
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: 3.7,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: 5.5,
              z: [
                3.8,
                7.6
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: 1.6,
          z: 2.1
        }
      ],
      board: [
        -3.1,
        0,
        -1.4
      ]
    },
    {
      items: [
        {
          type: 'stove',
          x: -0.8,
          z: 5.9,
          yaw: 0
        },
        {
          type: 'saltbox',
          x: 4.5,
          z: 1.1,
          n: 2,
          offset: 1
        },
        {
          type: 'wall',
          x: 4.3,
          z: 5.4,
          along: 'z',
          n: 3,
          rows: 2,
          yaw: 0.15
        },
        {
          type: 'hurdle',
          x: 2.4,
          z: 2.1,
          w: 2.6,
          yaw: -0.25
        },
        {
          type: 'fruit',
          lanes: [
            {
              x: -2.4,
              z: [
                -2.8,
                0.6
              ]
            },
            {
              x: 6,
              z: [
                3.8,
                7.6
              ]
            }
          ]
        },
        {
          type: 'bowl',
          x: -5.1,
          z: 1.9
        }
      ],
      board: [
        4.8,
        0,
        -1.4
      ]
    }
  ]
};
